### ISSUE TITLE
HostSynonyms column is empty

### ISSUE THREAD

**Issue by lbrierley** [viralemergence/virion#42]
Not sure if deprecated but this contains no data. If deprecated/for future release a data dictionary would help here! 🙂

**Comment by cjcarlson** [comment]
yeah, this is one Rory and I gotta sort. maybe one for the next Devs call - @renatamuy and I were talking about this too. I think what we need to do is either (1) add it all to the host metadata file post-split or (2) just give people a short version of `findSyns` basically that they can use, but either way I think we probably want to remove this field from the final architecture

**Comment by cjcarlson** [comment]
Temporary fix implemented in 8654517c75e44b25e573cb65aef76d01f42b180a while we decide what we'd like to do with this in the longer term.

**Comment by cjcarlson** [comment]
Actually, I'll open a long-term issue for that
