### ISSUE TITLE
NA or empty string to mark missing data?

### ISSUE THREAD

**Issue by tpoisot** [viralemergence/virion#46]
Do we want to replace the `NA` by no string at all in the master file? I know that R usually converts them on the fly to a NA, but other CSV readers (`pandas` in python and `CSV` in Julia, not to mention Excel) might not.

If we want to keep `NA` (fine by me by the way), I'll open a PR to make it explicit in the README.

**Comment by cjcarlson** [comment]
hmm yeah let's see if we can do that safely

**Comment by cjcarlson** [comment]
Great news! It looks like we can almost certainly implement this safely. I'm not sure about base R, but read_csv / write_csv definitely handle this safely. So I'm thinking in the next version, we'll implement this and remove HostSynonyms

**Comment by cjcarlson** [comment]
Implemented in 8654517c75e44b25e573cb65aef76d01f42b180a
