### ISSUE TITLE
add a reference text

### ISSUE THREAD

**Issue by renatamuy** [viralemergence/virion#57]
Just update some hanta data in virion as:

`virion %>%
  mutate(PublicationYear = replace(PublicationYear, NCBIAccession == 'MF094269', 2018)) %>%
  mutate(ReferenceText = replace(ReferenceText, NCBIAccession == 'MF094269', 'https://doi.org/10.1038/s41598-018-27442-w')) %>% 
  mutate(PublicationYear = replace(PublicationYear, NCBIAccession == 'MF094267', 2018)) %>%
  mutate(ReferenceText = replace(ReferenceText, NCBIAccession == 'MF094267', 'https://doi.org/10.1038/s41598-018-27442-w')) %>% 
  as.data.frame()`

**Comment by cjcarlson** [comment]
Hey Renata, can you give me some more context on this one?

**Comment by renatamuy** [comment]
Hey, it is just the article (year and doi) from where the information comes from :). The info was missing for the 2 samples.

**Comment by cjcarlson** [comment]
What's the data source on these records? If it's CLOVER it's something to pass onto Rory, but so far we haven't manually corrected any records outside CLOVER

**Comment by renatamuy** [comment]
Oh yeah, wrong source to change, my bad. I will find it there and open an issue. Thanks, Colin!
